# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_culex_stochastic <- function(p, tau_E, tau_L, tau_P, dt, psi) {
    .Call('_culex_create_culex_stochastic', PACKAGE = 'culex', p, tau_E, tau_L, tau_P, dt, psi)
}

step_culex_stochastic <- function(mod, parameters) {
    invisible(.Call('_culex_step_culex_stochastic', PACKAGE = 'culex', mod, parameters))
}

set_A_stochastic <- function(mod, A) {
    invisible(.Call('_culex_set_A_stochastic', PACKAGE = 'culex', mod, A))
}

get_A_stochastic <- function(mod) {
    .Call('_culex_get_A_stochastic', PACKAGE = 'culex', mod)
}

get_E_stochastic <- function(mod) {
    .Call('_culex_get_E_stochastic', PACKAGE = 'culex', mod)
}

get_L_stochastic <- function(mod) {
    .Call('_culex_get_L_stochastic', PACKAGE = 'culex', mod)
}

get_P_stochastic <- function(mod) {
    .Call('_culex_get_P_stochastic', PACKAGE = 'culex', mod)
}

create_culex_deterministic <- function(p, tau_E, tau_L, tau_P, dt, psi) {
    .Call('_culex_create_culex_deterministic', PACKAGE = 'culex', p, tau_E, tau_L, tau_P, dt, psi)
}

step_culex_deterministic <- function(mod, parameters) {
    invisible(.Call('_culex_step_culex_deterministic', PACKAGE = 'culex', mod, parameters))
}

set_A_deterministic <- function(mod, A) {
    invisible(.Call('_culex_set_A_deterministic', PACKAGE = 'culex', mod, A))
}

get_A_deterministic <- function(mod) {
    .Call('_culex_get_A_deterministic', PACKAGE = 'culex', mod)
}

get_E_deterministic <- function(mod) {
    .Call('_culex_get_E_deterministic', PACKAGE = 'culex', mod)
}

get_L_deterministic <- function(mod) {
    .Call('_culex_get_L_deterministic', PACKAGE = 'culex', mod)
}

get_P_deterministic <- function(mod) {
    .Call('_culex_get_P_deterministic', PACKAGE = 'culex', mod)
}

rcpparma_hello_world <- function() {
    .Call('_culex_rcpparma_hello_world', PACKAGE = 'culex')
}

rcpparma_outerproduct <- function(x) {
    .Call('_culex_rcpparma_outerproduct', PACKAGE = 'culex', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_culex_rcpparma_innerproduct', PACKAGE = 'culex', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_culex_rcpparma_bothproducts', PACKAGE = 'culex', x)
}

